import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import { parse as yaml } from 'yaml';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const ajv=new Ajv2020({allErrors:true,strict:true}); const names=['token-library','architecture-model','policy-set','validation-report','renderer-input'];
const schemas=Object.fromEntries(names.map(n=>{const s=JSON.parse(fs.readFileSync(path.join(root,'schema',`${n}.schema.json`)));if(!ajv.validateSchema(s))throw new Error(`${n} schema invalid: ${fmt(ajv.errors)}`);return[n,ajv.compile(s)]})); let failures=0;
const fail=x=>{failures++;console.error(`FAIL: ${x}`)}; const load=p=>yaml(fs.readFileSync(p,'utf8')); const fmt=e=>(e??[]).map(x=>`${x.instancePath||'/'} ${x.message}`).join('; '); const diag=(code,severity,layer,path,message,extra={})=>({code,severity,layer,path,message,...extra});
export function validateArchitecture(model,libraries,policies=[]){
 const ds=[]; const declared=new Set(model.libraries??[]); const libs=new Map(libraries.map(x=>[`${x.namespace}@${x.version}`,x])); for(const x of declared)if(!libs.has(x))ds.push(diag('PACKAGE_VERSION_MISMATCH','error','references','/libraries',`Library ${x} is unavailable`));
 const tm=new Map(); const libIds=new Map(); for(const l of libraries){for(const t of l.tokens){if(!l.domains?.includes(t.id.split('.')[0]))ds.push(diag('TOKEN_NAMESPACE_MISMATCH','error','references','/tokens',`${t.id} is outside ${l.namespace} domains`));const k=`${l.namespace}:${t.id}`;if(tm.has(k))ds.push(diag('DUPLICATE_TOKEN_ID','error','references','/tokens',`Duplicate ${k}`));tm.set(k,{...t,namespace:l.namespace,version:l.version,ref:k});}if(libIds.has(`${l.namespace}@${l.version}`))ds.push(diag('DUPLICATE_LIBRARY_ID','error','references','/libraries',`Duplicate library ${l.namespace}@${l.version}`));libIds.set(`${l.namespace}@${l.version}`,l)}
 const comps=new Map(model.components.map(e=>[e.id,{...e,elementKind:'component'}])); const rels=new Map(model.relationships.map(e=>[e.id,{...e,elementKind:'relationship'}]));
 for(const [kind,arr] of [['component',model.components],['relationship',model.relationships]]){const seen=new Set();for(const e of arr){if(seen.has(e.id))ds.push(diag('DUPLICATE_ELEMENT_ID','error','references',`/${kind}s/${e.id}`,`Duplicate ${e.id}`,{elementId:e.id}));seen.add(e.id)}}
 const ref=(r,expected,p,id)=>{const t=tm.get(r);if(!t){ds.push(diag('UNRESOLVED_TOKEN','error','references',p,`Unresolved ${r}`,{elementId:id}));return null}if(expected&&t.kind!==expected)ds.push(diag('WRONG_TOKEN_KIND','error','semantics',p,`Expected ${expected}`,{elementId:id}));const ns=r.split(':')[0];if(!declared.has(`${ns}@${t.version}`))ds.push(diag('UNDECLARED_LIBRARY_TOKEN','error','references',p,`${r} is not from a declared library`,{elementId:id}));return t};
 for(const e of [...comps.values(),...rels.values()]){const type=ref(e.type,e.elementKind==='component'?'component-type':'relationship-type',`/${e.elementKind}s/${e.id}/type`,e.id);if(type?.valueSchema&&!ajv.compile(type.valueSchema)(e.configuration??{}))ds.push(diag('INVALID_TYPE_CONFIGURATION','error','semantics',`/${e.elementKind}s/${e.id}/configuration`,'Invalid type configuration',{elementId:e.id}));const apps=e.tokens;const refs=apps.map(a=>a.token);for(const r of refs)if(refs.filter(x=>x===r).length>1)ds.push(diag('DUPLICATE_APPLICATION','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`Duplicate ${r}`,{elementId:e.id}));for(const a of apps){const t=ref(a.token,'applied',`/${e.elementKind}s/${e.id}/tokens`,e.id);if(!t)continue;const ap=t.appliesTo;if(ap&&(!ap.elementKinds?.includes(e.elementKind)||(e.elementKind==='component'&&ap.componentTypes&&!ap.componentTypes.includes(e.type))||(e.elementKind==='relationship'&&ap.relationshipTypes&&!ap.relationshipTypes.includes(e.type))))ds.push(diag('TOKEN_NOT_APPLICABLE','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`${a.token} not applicable`,{elementId:e.id}));if(a.value!==undefined&&!t.valueSchema)ds.push(diag('UNEXPECTED_TOKEN_VALUE','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`${a.token} has no value schema`,{elementId:e.id}));if(t.valueSchema&&a.value===undefined)ds.push(diag('INVALID_TOKEN_VALUE','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`${a.token} requires a value`,{elementId:e.id}));if(t.valueSchema&&a.value!==undefined&&!ajv.compile(t.valueSchema)(a.value))ds.push(diag('INVALID_TOKEN_VALUE','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`Invalid ${a.token}`,{elementId:e.id}));for(const q of t.requires??[])if(!refs.includes(q))ds.push(diag('TOKEN_REQUIRES','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`${a.token} requires ${q}`,{elementId:e.id}));for(const q of t.conflicts??[])if(refs.includes(q))ds.push(diag('TOKEN_CONFLICT','error','semantics',`/${e.elementKind}s/${e.id}/tokens`,`${a.token} conflicts ${q}`,{elementId:e.id}))}}
 for(const r of rels.values())for(const x of [r.from,r.to])if(!comps.has(x))ds.push(diag('UNRESOLVED_ELEMENT','error','references',`/relationships/${r.id}`,`Unresolved ${x}`,{elementId:r.id}));
 const matches=(e,c)=>{if(!c)return true;if(c.kind&&e.elementKind!==c.kind)return false;if(c.type&&e.type!==c.type)return false;const rs=e.tokens.map(x=>x.token);if(c.hasToken&&!rs.includes(c.hasToken))return false;if(c.missingToken&&rs.includes(c.missingToken))return false;if(c.connectedTo){const q=c.connectedTo;return [...rels.values()].filter(r=>(q.direction==='in'?r.to===e.id:q.direction==='out'?r.from===e.id:r.from===e.id||r.to===e.id)&&(!q.relationshipType||r.type===q.relationshipType)).some(r=>{const other=comps.get(r.from===e.id?r.to:r.from);return other&&(!q.elementType||other.type===q.elementType)&&(!q.elementToken||other.tokens.map(x=>x.token).includes(q.elementToken))})}return true};const ev=(e,c)=>c?.all?c.all.every(x=>ev(e,x)):c?.any?c.any.some(x=>ev(e,x)):c?.not?!ev(e,c.not):matches(e,c);
 for(const p of policies.flatMap(x=>x.policies??[])){const es=p.target==='component'?[...comps.values()]:p.target==='relationship'?[...rels.values()]:[{id:model.id,elementKind:'model',...model}];for(const e of es)if(ev(e,p.where)&&!ev(e,p.assert))ds.push(diag('POLICY_VIOLATION',p.severity,'policy',`/policies/${p.id}`,p.message,{elementId:e.elementKind==='model'?undefined:e.id,ruleId:p.id}))}
 return {valid:!ds.some(x=>x.severity==='error'),diagnostics:ds};
}
export function normalizeArchitecture(model,libraries){const tm=new Map(libraries.flatMap(l=>l.tokens.map(t=>[`${l.namespace}:${t.id}`,{definition:{...t,namespace:l.namespace,ref:`${l.namespace}:${t.id}`}}])));const n=e=>({id:e.id,type:{definition:tm.get(e.type)?.definition??{ref:e.type}},appliedTokens:e.tokens.map(a=>({token:tm.get(a.token)??{definition:{ref:a.token}},...(a.value===undefined?{}:{value:a.value})})),configuration:e.configuration??{},...(e.from?{from:e.from,to:e.to}:{})});return{kind:'renderer-input',model:{id:model.id,components:model.components.map(n),relationships:model.relationships.map(n)}}}
const libs=fs.readdirSync(path.join(root,'libraries')).filter(x=>x.endsWith('.yaml')).map(x=>load(path.join(root,'libraries',x)));for(const l of libs)if(!schemas['token-library'](l))fail(`library invalid: ${fmt(schemas['token-library'].errors)}`);
for(const f of fs.readdirSync(path.join(root,'examples')).filter(x=>x.endsWith('.yaml'))){const d=load(path.join(root,'examples',f));const n=d.kind==='architecture-model'?'architecture-model':'policy-set';if(!schemas[n](d))fail(`${f} schema invalid: ${fmt(schemas[n].errors)}`);if(n==='architecture-model'){if(!schemas['renderer-input'](normalizeArchitecture(d,libs)))fail(`${f} renderer input invalid: ${fmt(schemas['renderer-input'].errors)}`);const p=load(path.join(root,'examples/policies.yaml'));const r=validateArchitecture(d,libs,[p]);if(!r.valid)fail(`${f} should pass shipped policies: ${r.diagnostics.map(x=>x.code).join(',')}`)}}
for(const f of fs.readdirSync(path.join(root,'tests/schema-invalid')).filter(x=>x.endsWith('.yaml'))){const d=load(path.join(root,'tests/schema-invalid',f));if(schemas['architecture-model'](d))fail(`${f} should fail schema`);else console.log(`PASS: schema-invalid/${f}`)}
for(const f of fs.readdirSync(path.join(root,'tests/semantic-invalid')).filter(x=>x.endsWith('.yaml'))){const d=load(path.join(root,'tests/semantic-invalid',f));if(!schemas['architecture-model'](d)){fail(`${f} is not schema-valid`);continue}const p=load(path.join(root,'examples/policies.yaml'));const r=validateArchitecture(d,libs,[p]);if(f==='policy-violations.yaml'){const ids=r.diagnostics.filter(x=>x.code==='POLICY_VIOLATION').map(x=>x.ruleId);if(!ids.includes('production-database-encryption')||!ids.includes('production-database-not-public'))fail('policy rules missing');}else if(r.valid)fail(`${f} should fail semantically`);else console.log(`PASS: semantic-invalid/${f}`)}
if(failures){process.exitCode=1;console.error(`${failures} failure(s)`)}else console.log('All specification checks passed.');
